### ISSUE TITLE
Plugin generator should ask for activation and deactivation hook generation

### ISSUE THREAD

**Issue by ocReaper** [wolfika/generator-wp-suite#9]
Hi @wolfika,

Running empty functions on activation and deactivation of the plugin is really unnecessary, so the generator should ask if you need such functions.

**Comment by wolfika** [comment]
Hi @ocReaper,

Thank you for the suggestion, good idea. But as the generator is beginning to have more and more questions regarding the removal of some boilerplate parts, I think it might be a better idea to remove all these questions, and implement a list selection instead. Something like this: http://stackoverflow.com/a/25530535
